### ISSUE TITLE
NOT issue its a suggestion

### ISSUE THREAD

**Issue by LKA1337** [ralphkb/sentinel-tickets#1]
its not issue its a suggestion can you maybe add something like if i close the ticket then i get a dm frome the bot with whoclosed/who is owner of ticket/claimed or not and can you maybe add transcripts in .txt 

(the dm after ticket close) Example:
![test](https://github.com/ralphkb/sentinel-tickets/assets/128521854/8675ed22-1678-4879-992e-482a110f7b39)

**Comment by ralphkb** [comment]
Hello,
I added the DM user feature in the latest commit, I will also look into adding a .txt transcript feature soon and will try to put some templates up for both bug reports and suggestions here.

Thank you for your suggestions and for using the bot! 😄

**Comment by ralphkb** [comment]
The .txt transcript option has been added now, however I would still recommend using HTML transcripts when possible since it is more elegant and doesn't have as many limitations as the .txt option.

I will be closing this issue now that the suggestions have been added, feel free to create a new one in case of a bug report or other suggestions, I will take a look at them in my free time. 😃
