### ISSUE TITLE
Add a reason and list feature to the blacklist system

### ISSUE THREAD

**Issue by mrkingtj** [ralphkb/sentinel-tickets#16]
As the title suggests, add a reason to the system and a way to view the banned users, when (with a dynamic timestamp like <t:1708673880:R> for example)  they were banned, by who and why (the reason)

Not too sure how this could be set out but might be something handy. Aswell as maybe add a reason to the unblacklist.
Could be a command like `/blacklist info` and shows all that information aswell as retaining the existing `/unblacklist` and `/blacklist` commands (as to be fair are handy as)

**Comment by ralphkb** [comment]
Hey, thanks for your suggestion and I agree the blacklist system can benefit from a lot of improvements at some point in the future. Not sure when I'll get to it but it will also require a change in how it stores roles and users in the database, so I think I'll only post an update for the blacklist once I can get to polishing it all at once since it would require users to re-blacklist previously blacklisted users since I don't think I can change it without having users redo their blacklist.

I intend to make it store roles and users differently than how it does it now which would allow the creation of a command to list blacklisted users later on when I get to it.

**Comment by ralphkb** [comment]
Hey @Mirrage0, the features you requested for the blacklist have been added now in the commit bfed7a2.
I recoded the blacklist system such that it is now 1 command which has 3 subcommands, add, remove and list.
You can now see the information you requested in `/blacklist list`, it has optional arguments for the page and type such as Users or Roles. It will display the blacklisted users/roles, the staff who blacklisted them, the time in the form of a timestamp and the reason.
Note that reason is optional and if not provided, it will default to "No reason provided".

Regarding your previous off-topic question, it seems the only platform I can use for that would be patreon so I plan on setting it up alongside a discord server in the future as well for support with the bot in my free time. If you are still interested, you can also give me ideas regarding the patreon or by DM on discord.

Thank you for your suggestions and for reporting issues, I appreciate that! 😄
