### ISSUE TITLE
Bug add user

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#25]
When someone is added to the ticket and the ticket is closed, the person is not removed from the ticket

**Comment by ralphkb** [comment]
Hello, this is not a bug but rather how the feature is meant to work. The `closeRemoveUser` config option only applies to the ticket creator currently and otherwise if you add someone to a ticket and close it, their permissions to send messages are correctly modified.

I may look into adding another option that would also remove other added users upon ticket closure but then it would be a feature request and not a bug.
