### ISSUE TITLE
Bug send massage blacklist

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#26]
![Screenshot 2024-04-03 221637](https://github.com/ralphkb/sentinel-tickets/assets/133818503/e677e601-430f-47f6-a906-b67ded492cbf)
![Screenshot 2024-04-03 221607](https://github.com/ralphkb/sentinel-tickets/assets/133818503/4f0402e5-bc3c-414b-aa97-59e276583571)

**Comment by ralphkb** [comment]
Hey, this is not a bug but an issue with your config being outdated while you did update other files. You should always keep your config updated with any additions I make alongside also updating the other files, otherwise you might run into such issues.
In this case, please redo your config and make sure everything is added correctly, then it should work fine.
