### ISSUE TITLE
alart update

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#35]
- /alert can be selected to go to the person added in the ticket or to the person who owns the ticket

e.g= /alart (user)

**Comment by ralphkb** [comment]
Hello, this feature has been added in the latest commit now. You might need to use `/reload` after updating your files for the `/alert` command to show the new optional user option.
By default if you don't use the new option, it will alert the ticket creator. It will also check to see if the user you select is added to the ticket, otherwise a reply error will be sent about that.

Thanks for the suggestion.
