### ISSUE TITLE
Custom modal to ticketTopic

### ISSUE THREAD

**Issue by mrc4tt** [ralphkb/sentinel-tickets#38]
Hey.

It would be great if there was an option to add {custom-modal1} to ticketTopic.

For example, methods:
- I press 'create ticket' and get a modal popup on my screen where I have to type this number, for example 133700

- The ticket is created and I will see this 133700 on the channel topic.

Could this be possible, based on this custom modal?

**Comment by ralphkb** [comment]
Hello, I think what you're suggesting is basically a modal when opening a ticket which will allow the users to input a channel topic.
This is currently not possible since it would require me to give up a slot of the 5 questions of the modal, which is a discord limitation of all modals. In the current implementation I cannot add this but maybe in the future at some point I might look into a way to use more than one modal which would make this a possibility.

However I could add a `/topic` slash command if you want, which would allow the modification of the channel topic. Since the permissions for the command can also be edited, you could allow your users to have access to it and then they would be able to change their ticket topic even after opening the ticket.

**Comment by mrc4tt** [comment]
I'm not asking for 5 questions of the modals, as I only need to use 1. :-)

Here is what I mean:
- ralphkb press "open ticket button"
- ralphkb typing on the 1 only modal: 1337000 and press submit.
- Bot will create the ticket channel, this is what you can see on the channel's topic: `Ticket Creator: {user} | Ticket Type: {type} | {custom-modal1}`

Example output:
Ticket Creator: ralphkb | Ticket Type: Support | 1337000
