### ISSUE TITLE
Error creating ticket

### ISSUE THREAD

**Issue by Mirrage0** [ralphkb/sentinel-tickets#48]
Error:
```
Error creating ticket: TypeError: Cannot read properties of undefined (reading 'children')
    at findAvailableCategory (C:\Users\epicg\Desktop\premiumbot\index.js:203:35)
    at C:\Users\epicg\Desktop\premiumbot\events\interactionCreate.js:2008:46
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
This occurs when creating a ticket (after modal sumbission) in this function:
```js
// Find the first available category ID
const findAvailableCategory = async (categoryIDs) => {
  for (const categoryID of categoryIDs) {
    const category = client.channels.cache.get(categoryID);
    const channelCount = category.children.cache.size;
    if (channelCount < 50) {
      return categoryID;
    }
  }
  return null; // No available category found
};
```
This is using the latest commit

**Comment by ralphkb** [comment]
Hey, make sure to also update your configuration because categoryID and closedCategoryID are now both arrays so if you had it as "ID" it should now become ["ID"] instead.
Also ensure the bot has enough permissions in the category to see all the channels.

**Comment by ralphkb** [comment]
Yes, those are now arrays so even if you use only 1 category you must update it from the old string "ID" to the new array ["ID"]

The commit which had this change also had a config update with examples:
```YAML
    categoryID: ["111111111111111111"] # The IDs of the categories where those tickets will be created, for example ["000000000000000000", "111111111111111111"]
    closedCategoryID: ["111111111111111111"] # The IDs of the categories where the closed tickets will go, for example ["000000000000000000", "111111111111111111"]
```

**Comment by ralphkb** [comment]
The rest of the config looks fine but in the future to make it easier to keep up with config updates I highly suggest using the compare plugin of notepad++ as it's easy to check for changes using it.

The error you sent above is not related to a config issue but it's also quite strange, it is related to the message the bot sent in the DM of the user and seems like the bot no longer had access to it somehow for it to return null.
Maybe the bot was blocked before the answer was submitted via the feedback modal?
Can you test it again with that in mind?

**Comment by ralphkb** [comment]
Yeah I tried testing it a few times and it seems to be working fine, the issue was possibly a bit of lag with the discord API given that the code that caused the error was fetching a message so it probably couldn't fetch it properly at that time.

I also use VSCode haha but given how lightweight and fast notepad++ is, it has it's own benefits on quickly editing or comparing configuration files too I think. Either way, good luck and thanks!

**Comment by ralphkb** [comment]
Try giving the bot Administrator permissions and then test again, so we can see if this is a permission issue at this point.

**Comment by ralphkb** [comment]
That is because the bot requires permission to be able to fetch the category and use that information to get the channel count correctly so it will use the fallback category if you have one that is full.
It should also work without Administrator permission but then you would have to dig a bit deeper in your permission configurations, such as giving the bot the needed permissions per category as necessary such as Manage Channels and more for the functionality of the bot to be full.
