### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by LKA1337** [ralphkb/sentinel-tickets#5]
Pleaseeee add that I can set which role sees which tickets for the individual topics, e.g. in questions only supporter can write/look in and in donation only owner can write/look in

that would be awesome

**Comment by ralphkb** [comment]
Hello, I think you mean dividing the support roles per ticket category instead of having them generally for all the categories.
I might consider changing this at some point in the future, please use the correct issue template for feature requests next time.
Thanks.

**Comment by ralphkb** [comment]
Hey, I'm not sure why you closed this issue as completed yesterday but this new feature has been added now in the latest commit.
I changed it so that each ticket category can have it's own support roles and ping roles on ticket creation.

The blacklist commands however are not per ticket category, so there is a new config option to specify which support roles should have access to the blacklist and unblacklist commands.

Thank you for your suggestion!
