### ISSUE TITLE
InteractionAlreadyReplied

### ISSUE THREAD

**Issue by mods-hd** [ralphkb/sentinel-tickets#50]
**Describe the bug**
InteractionAlreadyReplied

**To Reproduce**
When use delete/transcript/close command on some ticket channel it will said this (heppen when bot online for a while [Not sure])

**Expected behavior**
Ticket bot will thinking and no response

**Screenshots**
![image](https://github.com/ralphkb/sentinel-tickets/assets/85879710/f2b8e3e1-c7ff-4d0a-9d11-d4330673ac76)

**Logs**
TypeError: Cannot read properties of undefined (reading 'id')
    at Object.execute (C:\Users\HP\Desktop\BOT\Ticket\commands\Tickets\delete.js:87:37)       
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (C:\Users\HP\Desktop\BOT\Ticket\events\interactionCreate.js:195:9)
Error [InteractionAlreadyReplied]: The reply to this interaction has already been sent or deferred.
    at ChatInputCommandInteraction.reply (C:\Users\HP\Desktop\BOT\Ticket\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:102:46)
    at Object.execute (C:\Users\HP\Desktop\BOT\Ticket\events\interactionCreate.js:198:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InteractionAlreadyReplied'
}

**Comment by ralphkb** [comment]
Hello, I'm not sure which version of the bot you're currently using but some commits after the latest 1.3.0 release have a fix for this issue. This happens when you restart the bot while a ticket is still opened, it would cause cache issues and would no longer let you delete/transcript/close a ticket.

Please update to the latest commit to make use of the fix and sort that issue out, also make sure to update the configuration while upgrading because some changes happened as well.

**Comment by ralphkb** [comment]
Hey @mods-hd, please try redownloading all the files from the repository (not the release section) and update all of them then restart your bot after ensuring your configuration is also updated based on the commit changes and latest config.yml.example

The error you sent above does not match the lines of code I see in the latest versions of the files, so they are likely a bit behind. I cannot replicate the issue and I already fixed it in one of the commits a few days ago.
In case this somehow still happens again, please send logs from logs.txt next time since they give more useful information as well.
