### ISSUE TITLE
Add CMD info {user} 

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#58]
-  /infouser @TeaR
 Display the history of the person
History of being blacklisted
History of making tickets
History add & rt

**Comment by ralphkb** [comment]
Hey, adding this currently would not be useful since the bot does not track any history of blacklisting or making tickets. If such data is added in the future then I can make a command to display it but for now the only user info command the bot has is the context menu command which will display some useful information like the user ID, avatar, when they joined discord and your server.

Thanks for the suggestion but it is currently not planned for the near future.
