### ISSUE TITLE
command for users

### ISSUE THREAD

**Issue by SSSXOX** [ralphkb/sentinel-tickets#63]
A command where each server user can set which DM messages they want to receive from the bot

**Comment by ralphkb** [comment]
Hello, I agree that adding a command for users to set their own DM preferences with the bot can be a useful addition.
I will keep this issue open until I get to adding this, thanks for the idea.

**Comment by ralphkb** [comment]
This is now added in this commit: 400d260

Note that I decided not to add an option for them to edit their delete DM preference since I think every user should get that one as it contains really important information and also the rating system. I might change my mind in the future and decide to add an option for it but we will see.

Thank you for the suggestion.
