### ISSUE TITLE
Update Embed Command Stats

### ISSUE THREAD

**Issue by MahdiTeaR** [ralphkb/sentinel-tickets#68]
Automatic update command stats

**Comment by ralphkb** [comment]
Hey, while the idea of showing some statistics is great, I will not be adding it in such an inefficient way. I think a better approach for this would be locked voice channels at the top of the channels list which would automatically update the statistics by renaming the channel every 10 minutes (due to discord's channel renaming rate limits).

I will look into adding this in the future, an example for this would be a locked voice channel like: `Total Tickets: 577` or so.
Thanks for the suggestion.
