### ISSUE TITLE
A few feature requests for future builds

### ISSUE THREAD

**Issue by Mirrage0** [ralphkb/sentinel-tickets#7]
`-` When a ticket is closed it should update the channel perms so only the support role(s) can see the channel but cant send messages (maybe?) and can still interact with the buttons.

`-` When a ticket is claimed update channel perms so the support roles send message perm is denied but keep the ticket claimer and the ticket author as normal, like 1 on 1 support. Unclaiming/transferring the claim should update perms respectively.

`-` When a ticket is closed, a little information about the ticket should be DMed to the user (especially if the channel permission updates are a thing) for ease of communication between staff to reopen tickets if needed

`-` When a ticket is reopened should DM the user that their ticket was reopened

`-` Add an option to choose a channel ID in the config for a separate channel for the feedback/reviews as it can clog up and make it all messy in the long run

(Of course, you do not have to add any of these and are fully entitled to put your own flare to it as you wish! Got to keep ideas on the table of where to go next right?)

**Comment by ralphkb** [comment]
Hello, thank you for submitting your suggestions!

I agree that even though they may or may not be added, it is always nice to have more ideas to keep the project going and evolving based on feedback. I also try to provide as many configurable options as possible so that more people can modify the config based on their own needs.

I will see what I can do regarding these suggestions moving forward and will try to implement them at some point.

**Comment by ralphkb** [comment]
Suggestions 1 & 3 have been added in the last 2 commits.

The option to remove the user upon the closure of a ticket should cover suggestion 1, it will still keep the support roles without them being able to chat but they can interact with the buttons.
The option to DM users upon ticket close has been added in a similar way to the reopen DM embed, in case you allow your users to close a ticket then they will not get a DM if they are the one who closed it.
