### ISSUE TITLE
Panel types

### ISSUE THREAD

**Issue by TsukiyoDevs** [ralphkb/sentinel-tickets#71]
Just looking at the config file, where does it define if the panel has buttons or a selection menu?

**Comment by ralphkb** [comment]
Hello, this is no longer a configuration option as of the latest changes I made to the panels system. It's in fact much simpler now, as long as you configured your ticket categories correctly you can send panels with buttons or menu directly from within the command itself instead of having to reconfigure that for each panel.
So for example, you can do `/panel id:1 Menu` to send the panel with id 1 using select menu. `/panel id:1 Buttons` will send the same panel with id 1 but using Buttons.

Refer to the documentation website for explained notes about the configuration sections: https://sentinel-tickets-docs.pages.dev/configuration/config/#multi-panel-settings

**Comment by ralphkb** [comment]
No worries haha, thank you for using the bot! 😄
