### ISSUE TITLE
quick question + feature request

### ISSUE THREAD

**Issue by TsukiyoDevs** [ralphkb/sentinel-tickets#72]
` 1. ` What is the defaults of the `/preference` command for each option?

` 2. ` Is it possible to have an option to make the buttons that is on the close ticket embed + the one thats sent in the ticket channel to be a select menu too? Keeps everything nice, clean and smooth

**Comment by ralphkb** [comment]
Hey, regarding your first question the preference is enabled by default for everyone so that it does not interfere by default with the DM options of the bot otherwise some users of the bot might get confused by enabling the DM embeds but noticing their users not receiving them.

Regarding your feature request, it should be possible and I can look into adding it.

**Comment by ralphkb** [comment]
Adding the menu option would be easy but making it work by responding to them as a menu instead of buttons will require adding more code for each of them which is not hard but currently would lead to some duplicated code. I will postpone the addition of this feature until I refactor the code into functions later.

**Comment by ralphkb** [comment]
Hey @TsukiyoDevs, the option to use a select menu in the close embed has been added in this commit: d46d59f
Using a select menu instead of buttons in some other embeds like the opening embed in each ticket will be added at some point soon as well, this is the start of a big refactoring of the code which will lead to more possibilities for the bot in the future.
Thanks for the suggestion.
