### ISSUE TITLE
I get an error message when I run the bot and install everything

### ISSUE THREAD

**Issue by Hamzaalaa1s** [ralphkb/sentinel-tickets#90]
error?
![IMG_2730](https://github.com/user-attachments/assets/b3c0413c-7069-4f77-8028-266b8fd47523)
![IMG_2729](https://github.com/user-attachments/assets/5681330e-fd30-474b-8150-fab7440d9362)

**Comment by ralphkb** [comment]
Hey @Hamzaalaa1s, this error is related to the environment in which you installed the bot. Not sure what the exact cause may be since I don't have any information about the versions you use but I suggest trying to install the latest version of NodeJS 18 or 20+, avoiding NodeJS 19. You should also delete your `node_modules` directory and then run `npm install` again after updating NodeJS.

**Comment by Hamzaalaa1s** [comment]
Thanks it works now! How to make a ticket channel?

**Comment by ralphkb** [comment]
You would have to setup the bot by updating the configuration based on your needs and how you see fit. Adding in the required channel IDs for log channels, category IDs for ticket categories and configuring panels. Then you can start the bot and send the panel in any channel you want which will allow you and your users to open tickets by using the panel buttons or menu.

You can use the comments in the config for guidance and check out the documentation website: https://sentineltickets.com/

Good luck!

**Comment by ralphkb** [comment]
Hello, I hope everything ended up working well for you. I'll be closing the issue now, good luck and feel free to open a new one if you run into further problems.
